---
title: "CV"
output: 
  html_document:
    toc: true
    toc_float: true
---

<br>

### Education

#### **Columbia University Mailman School of Public Health | New York, NY | Sept 2023 - Present**
##### *PhD Student in the Environmental Health Sciences Department*

<br>

#### **Barnard College, Columbia University | New York, NY | Sept 2017 - May 2021**
##### *B.A. Cell & Molecular Biology with Minor in Science, Policy, & Ethics*

##### Summa Cum Laude, Department Honors, Phi Beta Kappa (Fall 2020) 

##### Thesis: "Developmental Lead Exposure: Effects on Neural Developmental Processes and Cognitive Outcomes"

<br>

### Research Experience

#### **Columbia University Mailman School of Public Health | New York, NY | July - Aug 2023**
##### *Non-Student Short-Term Casual (Research Assistant) in the lab of Dr. Ami Zota*

* Investigated role of environmental factors and genetic mutations in uterine fibroids.
* Characterized patterns of genetic mutations in MED12 gene in uterine fibroids.

<br>

#### **Columbia University Mailman School of Public Health | New York, NY | May 2019 - May 2021**
##### *Undergraduate Researcher in the lab of Dr. Brandon Pearson*

* Investigated effects of extreme temperatures on aging and neurological disease.
* Examined role of environmental factors in repeat expansion diseases.

<br>

#### **Institute for Cancer Genetics, Columbia University | New York, NY | May 2018 - Aug 2018**
##### *Undergraduate Researcher in the lab of Dr. Swarnali Acharyya*

* Investigated role of metal-ion transporter ZIP14 in cancer and non-cancer induced cachexia.

<br>

### Work Experience

#### **National Human Genome Research Institute, NIH | Bethesda, MD | June 2021 - June 2023**
##### *Scientific Program Analyst in the Division of Genome Sciences, Extramural Research Program (Contracted via Axle Informatics; previously contracted via Ingenesis)*

* Served on NHGRI scientific management teams for IGVF (Impact of Genomic Variation on Function) Consortium and ENCODE (Encyclopedia of DNA Elements) Consortium, large consortia focusing on genome annotation and functional genomics.

* Served on NHGRI scientific management team for PhenX (Phenotypes and eXposures) Toolkit, a trans-NIH supported resource of standard protocols for epidemiological research.





